export const SOURCE_DESCRIPTIONS: Record<string, string> = {
  grants_gov: "U.S. federal grant opportunities across all agencies",
  sam_gov: "U.S. federal contract opportunities and awards",
  hrsa: "Health Resources and Services Administration grants",
  ted_eu: "European Union public procurement notices",
  ungm: "United Nations procurement opportunities",
  worldbank: "World Bank procurement and consulting opportunities",
  undp: "UNDP procurement notices and tenders",
  adb: "Asian Development Bank procurement opportunities",
  iadb: "Inter-American Development Bank project procurement",
  caribank: "Caribbean Development Bank procurement",
  edc_ca: "Export Development Canada financing opportunities",
  contracts_finder_uk: "UK government contracts and tenders",
  public_contracts_scotland: "Scottish public sector contracts",
  sell2wales: "Welsh public sector procurement opportunities",
  austender_au: "Australian government tenders and contracts",
  gets_nz: "New Zealand government electronic tendering",
  gebiz_sg: "Singapore government procurement portal",
  chilecompra_cl: "Chilean public procurement system",
  compranet_mx: "Mexican federal procurement platform",
  panamacompra_pa: "Panamanian public procurement system",
  comprar_ar: "Argentine public procurement portal",
  comprasestatales_uy: "Uruguayan state procurement system",
  contrataciones_py: "Paraguayan public procurement",
  honducompras_hn: "Honduran public procurement platform",
  baosem_dz: "Algerian public procurement portal",
  mdn_dz: "Algerian Ministry of Defense procurement",
  marchespublics_ma: "Moroccan public procurement system",
  marchespublics_tn: "Tunisian public procurement observatory",
  ghaneps_gh: "Ghana electronic procurement system",
  etenders_ng: "Nigerian electronic tendering platform",
  egp_bd: "Bangladesh electronic government procurement",
  philgeps_ph: "Philippines Government Electronic Procurement System",
  eperolehan_my: "Malaysian electronic procurement system",
  jetro_jp: "Japan External Trade Organization opportunities",
  d2b_kr: "South Korea Defense Acquisition Program Administration",
  pps_kr: "South Korea Public Procurement Service",
  seap_ro: "Romanian electronic public procurement",
  iu_pl: "Polish Armament Inspectorate procurement",
  doffin_no: "Norwegian public procurement database",
  evergabe_de: "German electronic procurement platform",
  marches_publics_fr: "French public procurement portal",
  acquistinretepa_it: "Italian public administration procurement",
  prozorro_ua: "Ukrainian transparent procurement system",
  tenderboard_bh: "Bahrain tender board",
  ppra_pk: "Pakistan Public Procurement Regulatory Authority",
  etenders_za: "South African National Treasury eTenders",
  canadabuys_ca: "Canadian federal procurement opportunities",
  caleprocure_ca: "California eProcure state contracts",
  dms_fl_us: "Florida Department of Management Services",
  ogs_ny_us: "New York Office of General Services",
  nato_act: "NATO Allied Command Transformation procurement",
  nato_bonfire: "NATO Headquarters Bonfire procurement portal",
  ncia_nato: "NATO Communications and Information Agency",
  nspa_nato: "NATO Support and Procurement Agency"
};

export function getSourceDescription(sourceId: string): string {
  return SOURCE_DESCRIPTIONS[sourceId] || "Public procurement and funding opportunities";
}

