INSERT INTO funding_sources (
  id,
  name,
  country,
  homepage,
  integration_type,
  auto_url,
  expected_results,
  active,
  last_sync,
  last_status,
  last_error,
  last_ingested,
  created_at,
  updated_at
) VALUES
  ("baosem_dz", "BAOSEM", "Algeria", "https://baosem.com/lang/en", "manual_url", NULL, 3082, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("mdn_dz", "Ministry of National Defence", "Algeria", "https://www.mdn.dz/", "manual_url", NULL, 12, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("comprar_ar", "COMPR.AR", "Argentina", "https://comprar.gob.ar/", "manual_url", NULL, 285, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("adb", "Asian Development Bank", "Multilateral", "https://www.adb.org/", "manual_url", NULL, 116, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("austender_au", "AusTender", "Australia", "https://www.tenders.gov.au/", "manual_url", NULL, 69, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("tenderboard_bh", "Tender Board", "Bahrain", "https://etendering.tenderboard.gov.bh/", "manual_url", NULL, 119, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("egp_bd", "e-GP", "Bangladesh", "https://www.eprocure.gov.bd/", "manual_url", NULL, 2363, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("canadabuys_ca", "CanadaBuys", "Canada", "https://canadabuys.canada.ca", "manual_url", NULL, 601, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("caribank", "Caribbean Development Bank", "Multilateral", "https://www.caribank.org/", "manual_url", NULL, 131, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("chilecompra_cl", "ChileCompra", "Chile", "https://www.mercadopublico.cl/Home", "manual_url", NULL, 1889, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("ted_eu", "TED Europe", "EU", "https://ted.europa.eu/", "ted_xml_zip", "https://ted.europa.eu/en/simap/xml-bulk-download", 137263, 1, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("marches_publics_fr", "State Public Contracts", "France", "https://www.marches-publics.gouv.fr/entreprise", "manual_url", NULL, 115, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("evergabe_de", "e-Vergabe", "Germany", "https://www.evergabe-online.de/", "manual_url", NULL, 875, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("ghaneps_gh", "GHANEPS", "Ghana", "https://www.ghaneps.gov.gh/", "manual_url", NULL, 54, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("honducompras_hn", "HonduCompras", "Honduras", "https://www.honducompras.gob.hn/", "manual_url", NULL, 0, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("iadb", "Inter-American Development Bank", "Multilateral", "https://projectprocurement.iadb.org/en", "manual_url", NULL, 4, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("acquistinretepa_it", "AcquistinretePA", "Italy", "https://www.acquistinretepa.it/", "manual_url", NULL, 20, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("jetro_jp", "JETRO", "Japan", "https://www.jetro.go.jp/en/", "manual_url", NULL, 110604, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("eperolehan_my", "ePerolehan", "Malaysia", "https://www.eperolehan.gov.my/", "manual_url", NULL, 163, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("compranet_mx", "Compranet", "Mexico", "https://compranet.hacienda.gob.mx/", "manual_url", NULL, 205, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("marchespublics_ma", "Marches Publics", "Morocco", "https://www.marchespublics.gov.ma/", "manual_url", NULL, 4985, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("nato_act", "NATO Allied Command Transformation", "NATO", "https://www.act.nato.int/", "manual_url", NULL, 4, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("nato_bonfire", "NATO HQ Bonfire Portal", "NATO", "https://nato.bonfirehub.com/", "manual_url", NULL, 6, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("ncia_nato", "NATO NCI Agency", "NATO", "https://www.ncia.nato.int/", "manual_url", NULL, 29, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("nspa_nato", "NATO Support and Procurement Agency", "NATO", "https://eportal.nspa.nato.int/", "manual_url", NULL, 116, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("gets_nz", "GETS", "New Zealand", "https://www.gets.govt.nz/", "manual_url", NULL, 240, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("etenders_ng", "eTenders", "Nigeria", "https://www.etenders.com.ng/", "manual_url", NULL, 175, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("doffin_no", "Doffin", "Norway", "https://www.doffin.no/en", "manual_url", NULL, 797, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("ppra_pk", "PPRA", "Pakistan", "https://www.ppra.org.pk/", "manual_url", NULL, 0, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("panamacompra_pa", "PanamaCompra", "Panama", "https://panamacompra.gob.pa/", "manual_url", NULL, 513, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("contrataciones_py", "Direc. Nacional Contrataciones Publicas", "Paraguay", "https://www.contrataciones.gov.py/", "manual_url", NULL, 127, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("philgeps_ph", "PhilGEPS", "Philippines", "https://notices.philgeps.gov.ph/", "manual_url", NULL, 5738, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("iu_pl", "Inspektorat Uzbrojenia", "Poland", "https://iu.wp.mil.pl/pl/", "manual_url", NULL, 0, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("seap_ro", "SEAP Romania", "Romania", "https://www.e-licitatie.ro/", "manual_url", NULL, 1134, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("public_contracts_scotland", "Public Contracts Scotland", "Scotland", "https://www.publiccontractsscotland.gov.uk/", "manual_url", NULL, 1067, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("gebiz_sg", "GeBIZ", "Singapore", "https://www.gebiz.gov.sg/", "manual_url", NULL, 312, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("etenders_za", "National Treasury eTenders", "South Africa", "https://etenders.treasury.gov.za/", "manual_url", NULL, 0, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("d2b_kr", "DAPA-FPBIS", "South Korea", "https://www.d2b.go.kr/", "manual_url", NULL, 1, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("pps_kr", "Public Procurement Service", "South Korea", "https://www.pps.go.kr/eng/index.do", "manual_url", NULL, 5648, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("worldbank", "The World Bank", "Multilateral", "https://www.worldbank.org/", "core_api", NULL, 499, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("marchespublics_tn", "Observatoire National des Marches Publics", "Tunisia", "http://www.marchespublics.gov.tn/onmp/content/index.php?lang=fr", "manual_url", NULL, 0, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("contracts_finder_uk", "Contracts Finder", "United Kingdom", "https://www.contractsfinder.service.gov.uk/", "manual_url", NULL, 777, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("prozorro_ua", "Prozorro", "Ukraine", "https://prozorro.gov.ua", "manual_url", NULL, 134483, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("undp", "UNDP Procurement Notices", "United Nations", "https://procurement-notices.undp.org/", "manual_url", NULL, 207, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("ungm", "UN Global Marketplace", "United Nations", "https://www.ungm.org/", "manual_url", NULL, 617, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("edc_ca", "Export Development Canada", "Canada", "https://www.edc.ca/", "manual_url", NULL, NULL, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("comprasestatales_uy", "Compras Estatales", "Uruguay", "https://comprasestatales.gub.uy/", "manual_url", NULL, 440, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("caleprocure_ca", "Cal eProcure", "USA", "https://caleprocure.ca.gov/pages/index.aspx", "manual_url", NULL, 280, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("dms_fl_us", "Florida DMS", "USA", "https://www.dms.myflorida.com/", "manual_url", NULL, 118, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("ogs_ny_us", "New York OGS", "USA", "https://ogs.ny.gov/", "manual_url", NULL, 0, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("sam_gov", "SAM.gov", "USA", "https://sam.gov", "core_api", NULL, 43634, 1, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("grants_gov", "Grants.gov", "USA", "https://www.grants.gov", "core_api", NULL, NULL, 1, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("hrsa", "HRSA Grants", "USA", "https://www.hrsa.gov", "core_api", NULL, NULL, 1, NULL, NULL, NULL, 0, datetime('now'), datetime('now')),
  ("sell2wales", "Sell2Wales", "Wales", "https://www.sell2wales.gov.wales/", "manual_url", NULL, 21, 0, NULL, NULL, NULL, 0, datetime('now'), datetime('now'));
